<a href="https://colab.research.google.com/github/NAIDU6768/THIRUMALANAIDU/blob/main/car_price_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing all libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.metrics import r2_score

load the data set with the help of pandas library

In [2]:
df=pd.read_csv('/content/car data.csv')

Summarize the data set

In [3]:
#displays the first 5 rows in the form of data frame
df.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [4]:
#displaying the information about the data that may contains the how many columns,rows present in the data set and displays the data type of the column
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_Name       301 non-null    object
 1   Year           301 non-null    int64
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64
 5   Fuel_Type      301 non-null    object
 6   Seller_Type    301 non-null    object
 7   Transmission   301 non-null    object
 8   Owner          301 non-null    int64
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB

In [5]:
#here we finds the null values are missing values
df.isnull().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

In [6]:
#displays the stastical information of the data set
df.describe()

              Year  Selling_Price  Present_Price     Kms_Driven       Owner
count   301.000000     301.000000     301.000000     301.000000  301.000000
mean   2013.627907       4.661296       7.628472   36947.205980    0.043189
std       2.891554       5.082812       8.644115   38886.883882    0.247915
min    2003.000000       0.100000       0.320000     500.000000    0.000000
25%    2012.000000       0.900000       1.200000   15000.000000    0.000000
50%    2014.000000       3.600000       6.400000   32000.000000    0.000000
75%    2016.000000       6.000000       9.900000   48767.000000    0.000000
max    2018.000000      35.000000      92.600000  500000.000000    3.000000

In [ ]:
df.shape #displays the shape of the dataset

separates categerial information

In [7]:
df['Fuel_Type'].value_counts()

Fuel_Type
Petrol    239
Diesel     60
CNG         2
Name: count, dtype: int64

In [8]:
df['Seller_Type'].value_counts()

Seller_Type
Dealer        195
Individual    106
Name: count, dtype: int64

In [9]:
df['Transmission'].value_counts()

Transmission
Manual       261
Automatic     40
Name: count, dtype: int64

encoding the related numerical values to the features

In [10]:
df.replace({'Fuel_Type':{'Petrol':0,'Diesel':1,'CNG':2}},inplace=True)
df.replace({'Seller_Type':{'Dealer':0,'Individual':1}},inplace=True)
df.replace({'Transmission':{'Manual':0,'Automatic':1}},inplace=True)

In [11]:
df.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,0,0,0,0
1,sx4,2013,4.75,9.54,43000,1,0,0,0
2,ciaz,2017,7.25,9.85,6900,0,0,0,0
3,wagon r,2011,2.85,4.15,5200,0,0,0,0
4,swift,2014,4.60,6.87,42450,1,0,0,0

separates the target value

In [12]:
from sklearn.preprocessing import LabelEncoder

In [13]:
lb=LabelEncoder()

In [14]:
df.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,0,0,0,0
1,sx4,2013,4.75,9.54,43000,1,0,0,0
2,ciaz,2017,7.25,9.85,6900,0,0,0,0
3,wagon r,2011,2.85,4.15,5200,0,0,0,0
4,swift,2014,4.60,6.87,42450,1,0,0,0

In [15]:
X=df[['Year','Present_Price','Kms_Driven','Fuel_Type',	'Seller_Type',	'Transmission',	'Owner']]
Y=df['Selling_Price']

In [16]:
X

,Year,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,2014,5.59,27000,0,0,0,0
1,2013,9.54,43000,1,0,0,0
2,2017,9.85,6900,0,0,0,0
3,2011,4.15,5200,0,0,0,0
4,2014,6.87,42450,1,0,0,0
...,...,...,...,...,...,...,...
296,2016,11.60,33988,1,0,0,0
297,2015,5.90,60000,0,0,0,0
298,2009,11.00,87934,0,0,0,0
299,2017,12.50,9000,1,0,0,0
300,2016,5.90,5464,0,0,0,0

In [17]:
Y

0       3.35
1       4.75
2       7.25
3       2.85
4       4.60
       ...
296     9.50
297     4.00
298     3.35
299    11.50
300     5.30
Name: Selling_Price, Length: 301, dtype: float64

In [18]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.1,random_state=2)

In [19]:

model=Lasso()

In [20]:
train=model.fit(X_train,Y_train)

In [21]:
train_predict_model=model.predict(X_train)

In [23]:

accuracy = r2_score(Y_train, train_predict_model)
print(accuracy)

0.8427856123435794

In [24]:
# Function to take user inputs and predict the car price
def predict_car_price():
    # User inputs
    year = int(input("Enter the year of the car: "))
    present_price = float(input("Enter the present price of the car (in lakhs): "))
    kms_driven = int(input("Enter the kilometers driven: "))
    fuel_type = int(input("Enter the fuel type (Petrol: 0, Diesel: 1, CNG: 2): "))
    seller_type = int(input("Enter the seller type (Dealer: 0, Individual: 1): "))
    transmission = int(input("Enter the transmission type (Manual: 0, Automatic: 1): "))
    owner = int(input("Enter the number of previous owners: "))

    # Creating a DataFrame for the input values
    input_data = pd.DataFrame([[year, present_price, kms_driven, fuel_type, seller_type, transmission, owner]],
                              columns=['Year', 'Present_Price', 'Kms_Driven', 'Fuel_Type', 'Seller_Type', 'Transmission', 'Owner'])

    # Predicting the price
    predicted_price = model.predict(input_data)

    # Displaying the predicted price
    print(f"The predicted selling price of the car is: {predicted_price[0]:.2f} lakhs")

# Call the function to predict car price
predict_car_price()

Enter the year of the car: 2017
Enter the present price of the car (in lakhs): 9.85
Enter the kilometers driven: 6900
Enter the fuel type (Petrol: 0, Diesel: 1, CNG: 2): 0
Enter the seller type (Dealer: 0, Individual: 1): 0
Enter the transmission type (Manual: 0, Automatic: 1): 0
Enter the number of previous owners: 0
The predicted selling price of the car is: 7.16 lakhs